FootballClub/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
  url(r'^$', 'match.views.index'),
  url(r'^account/', include('account.urls', namespace='account')),
  url(r'^accounts/', include('accounts.urls', namespace='accounts')),
  url(r'^admin/', include(admin.site.urls)),
  url(r'^match/', include('match.urls', namespace='match')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.conf.urls import patterns, url
from account import views

urlpatterns = patterns('',
  url(r'^$', views.index),
  url(r'^profile/$', views.profile, name='profile'),
	url(r'^list_player/(?P<user_id>.+)/$', views.edit, name='edit'),
	url(r'^delete/(?P<user_id>.+)/$', views.delete, name='delete'),
	url(r'^login/$', views.site_login, name='login'),
	url(r'^logout/$', views.site_logout, name='logout'),
	url(r'^register/$', views.register, name='register'),
	url(r'^list_player/$', views.list_player, name='list_player'),
)

match/urls.py
from django.conf.urls import patterns, include, url
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from match import views
admin.autodiscover()

urlpatterns = patterns('',
  url(r'^$', views.index, name='index'),
  url(r'^add/$', views.add, name='add'),
  url(r'^edit/(?P<match_id>\d+)/$', views.edit, name='edit'),
  url(r'^detail/(?P<match_id>\d+)/$', views.detail, name='detail'),
	url(r'^delete/(?P<match_id>\d+)/$', views.delete, name='delete'),
	url(r'^add_player/(?P<match_id>\d+)/$', views.add_player, name='add_player'),
	url(r'^remove_player/(?P<match_id>\d+)/$', views.remove_player, name='remove_player'),
  url(r'^calendar/$', views.calendar, name='calendar'),
  url(r'^get_match/$', views.get_match, name='get_match'),
)

match/models.py
from django.db import models
from django.contrib.auth.models import User

class Match(models.Model):
  name = models.CharField(max_length=100)
  time = models.DateTimeField(null=True, blank=True)
  place = models.CharField(max_length=200, blank=True)
  competitor = models.CharField(max_length=100, blank=True)
  result = models.CharField(max_length=100, null=True, blank=True)
  player = models.ManyToManyField(User, related_name='player', null=True, blank=True)
  creator = models.ForeignKey(User, blank=True, null=True)

  class Meta:
      ordering = ['-time']
      permissions = (
        ("can_modify", "Can modify match add,edit,delete"),
        ("can_joinmatch","Player can join match"),
      )
  def __unicode__(self):
      return self.name

class Club(models.Model):
  photo = models.ImageField(upload_to='img', blank=True)
  name = models.CharField(max_length=100,blank=True, null=True)
  address = models.CharField(max_length=200,null=True, blank=True)

class Comment(models.Model):
  creator = models.ForeignKey(User, blank=True, null=True)
  comment = models.TextField(max_length=400, blank=True, null=True)
  created = models.DateTimeField(auto_now_add=True)
  reason = models.TextField(max_length=400, blank=True, null=True)
  match = models.ForeignKey(Match)

match/forms.py
from match.models import Match, Comment
from django import forms
from django.forms import ModelForm

class MatchForm(ModelForm):
  class Meta:
    model = Match
    fields = ('name', 'time', 'place', 'competitor', 'result')
    widgets = {
      'time': forms.TextInput(attrs={'class':'form-control', 'id':'time'}),
      'name':forms.TextInput(attrs={'class':'form-control', }),
      'place':forms.TextInput(attrs={'class':'form-control', }),
      'competitor':forms.TextInput(attrs={'class':'form-control', }),
      'result':forms.TextInput(attrs={'class':'form-control', }),
    }

class CommentForm(ModelForm):
  class Meta:
    model = Comment
    exclude = ("creator", "created", "reason", "match")
    widgets = {
      'comment': forms.Textarea(attrs={'class':'form-control','rows':'3', 'id':'match_comment'}),
    }

match/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required, permission_required
from django.core.paginator import EmptyPage, Paginator, PageNotAnInteger
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from match.forms import MatchForm, CommentForm
from django.db.models import Q
from match.models import Match, Comment, Club
from django.contrib.auth.models import User
from match.email import *
import thread
import json
import time
from datetime import datetime

def index(request):
  place = ''
  competitor = ''
  start_time = ''
  end_time = ''
  fromdate = ''
  playername = ''
  is_search = False
  # search with place, competitor, player, date
  if 'place' in request.GET:
    place = request.GET['place']
  if 'competitor' in request.GET:
    competitor = request.GET['competitor']
  if 'fromdate' in request.GET:
    fromdate = request.GET['fromdate']
    string = str(request.GET['fromdate']).split('-')
    # convert time to datetimefield model
    start_time = time.strftime('%Y-%m-%d %H:%M:%S', time.strptime(string[0][:-1],'%B %d, %Y'))
    end_time = time.strftime('%Y-%m-%d %H:%M:%S', time.strptime(string[1][1:],'%B %d, %Y'))
  if 'start_time' in request.GET:
    start_time = request.GET['start_time']
  if 'end_time' in request.GET:
    end_time = request.GET['end_time']

  if 'playername' in request.GET:
    playername = request.GET['playername']
  if start_time and end_time:
    if not playername:
      matchs = Match.objects.filter(Q(place__contains=place) & Q(competitor__contains=competitor) & Q(time__gte=start_time, time__lte=end_time))
    else:
      matchs = Match.objects.filter(Q(place__contains=place) & Q(competitor__contains=competitor) & Q(time__gte=start_time, time__lte=end_time) & (Q(player__first_name__contains=playername) | Q(player__last_name__contains=playername))).distinct()
    is_search = True
  else:
    matchs = Match.objects.all()

  club = Club.objects.all()[0]

  # pagination
  paginator = Paginator(matchs,3)
  page = request.GET.get('page')
  try:
    matchs = paginator.page(page)
  except PageNotAnInteger:
    matchs = paginator.page(1)
  except EmptyPage:
    matchs = paginator.page(paginator.num_pages)

  return render(request, 'match/index.html', {'matchs' : matchs, 'club' : club, 'place': place, 'competitor': competitor, 'fromdate': fromdate, 'is_search': is_search, 'playername': playername})

# create a match
@login_required
@permission_required('match.can_modify')
def add(request):
  if request.method == 'POST':
    match = MatchForm(request.POST)
    if match.is_valid():
      new_match = match.save(commit=False)
      new_match.creator = request.user
      new_match.save()
      return HttpResponseRedirect(reverse('match:detail', args=[new_match.id]))
  else:
    match = MatchForm()

  return render(request, 'match/match_form.html', {'match_form' : match}, )

# edit a match
@login_required
@permission_required('match.can_modify')
def edit(request, match_id):
  match_obj = get_object_or_404(Match, pk=match_id)
  if request.method == 'POST' and match_obj:
    match = MatchForm(request.POST)
    if match.is_valid():
      match_obj = match.save(commit=False)
      match_obj.creator = request.user
      match_obj.id = match_id
      match_obj.save()
      return HttpResponseRedirect(reverse('match:detail', args=(match_obj.id,)))
  else:
    match = MatchForm(instance=match_obj)
  return render (request, 'match/match_form.html', {'match_form' : match, 'form_type' : 'edit', })

# delete a match
@login_required
@permission_required('match.can_modify')
def delete(request, match_id):
  match_obj = get_object_or_404(Match, pk=match_id)
  match_obj.delete()
  if 'is_ajax' in request.GET:
    return HttpResponse('success')
  else:
    return HttpResponseRedirect(reverse('match:index'))

# show detail a match
def detail(request, match_id):
  commentform = CommentForm()
  all_player = User.objects.filter(groups__name='player')
  match = get_object_or_404(Match, pk=match_id)
  has_player = change_list(match.player.all())
  is_modify = False
  if request.user.has_perm('match.can_modify'):
    is_modify = True
  else:
    all_player = match.player.all()
  if request.method == 'POST':
    if 'is_comment' in request.POST:
      comment = CommentForm(request.POST)
      if comment.is_valid():
        new_comment = comment.save(commit=False)
        new_comment.match = match
        new_comment.creator = request.user
        new_comment.save()

        return HttpResponseRedirect(reverse('match:detail', args=(match.id,)))

    if 'is_delete_comment' in request.POST and 'comment_id[]' in request.POST:
      comment_list = request.POST.getlist('comment_id[]')
      Comment.objects.filter(pk__in=comment_list).delete()

  context = {
    'has_player' : has_player,
    'all_player' : all_player,
    'match' : match,
    'is_modify' : is_modify,
    'is_join' : request.user in match.player.all(),
    'commentform' : commentform
  }
  return render(request,"match/detail.html", context)

# add player to match
def add_player(request, match_id):
  if request.method == 'POST':
    match = get_object_or_404(Match, pk=match_id)
    user = User.objects.get(pk=request.POST['user_id'])
    if user and match:
      match.player.add(user)
      thread.start_new_thread(send_join_remind_email, (user, match, ))
      response = []
      response_user = {}
      response_user['id'] = user.id
      response_user['username'] = user.username
      response_user['first_name'] = user.first_name
      response_user['last_name'] = user.last_name
      response_user['email'] = user.email
      response_user['pos'] = user.profile.pos
      response_user['num'] = user.profile.num
      response_user['contact'] = user.profile.contact
      response_user['avatar'] = str(user.profile.avatar)
      print user.profile.avatar
      response.append(response_user)
      return HttpResponse(json.dumps(response), content_type="application/json")
  return HttpResponse("failed")

# remove player from a match
def remove_player(request, match_id):
  if request.method == 'POST':
    match = get_object_or_404(Match, pk=match_id)
    user = User.objects.get(pk=request.POST['user_id'])
    if user and match:
      match.player.remove(user)
      thread.start_new_thread(send_unjoin_remind_email, (user, match, ))
      if None != request.POST['reason']:
        comment = Comment()
        comment.match_id = match_id
        comment.reason = request.POST['reason']
        comment.creator = request.user
        comment.save()
        # send reason to manager
        manager = User.objects.filter(groups__name='manager')
        for m in manager:
          thread.start_new_thread(send_reason_unjoin_email, (user, match, request.POST['reason'], m))
      return HttpResponse(comment.id)
  return HttpResponse("failed")

# show matches on calendar
def calendar(request):
  # create match from calendar
  if request.method == 'POST':
    match_form = MatchForm(request.POST)
    if match_form.is_valid():
      match = match_form.save(commit=False)
      match.creator = request.user
      match.save()
      return HttpResponse(match.id)
  else:
    return render(request, "match/calendar.html", )

# get match via ajax to show matches on calendar
def get_match(request):
  start = request.GET['start']
  end = request.GET['end']
  start_time = datetime.fromtimestamp(int(start))
  end_time = datetime.fromtimestamp(int(end))
  matchs = Match.objects.filter(Q(time__gte=start_time, time__lte=end_time)| Q(time__lt=start_time))
  response = []

  for match in matchs:
    match_item = {}
    match_item['id'] = match.id
    match_item['editable'] = True
    match_item['title'] = match.name
    match_item['start'] = match.time.isoformat()
    match_item['url'] = reverse('match:detail', args=(match.id,))
    match_item['allDay'] = False

    response.append(match_item)
  return HttpResponse(json.dumps(response), content_type="application/json")

def change_list(obj):
  result = ""
  for x in obj:
    result += str(x.id) + ','
  return result

templates/match/calendar.html
{% extends "base.html" %}

{% load staticfiles %}
{% block calendar %}active{% endblock %}
{% block extend_lib %}
	<link rel="stylesheet" href="{% static "bower_components/fullcalendar/fullcalendar.css" %}" />
	<script src="{% static "bower_components/fullcalendar/fullcalendar.js" %}"></script>
{% endblock %}

{% block content %}

	<div id='loading' style='display:none'>loading...</div>
	<div id="calendar"></div>

<div class="modal fade" id="mymodal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Add new match</h4>
      </div>
      <div class="modal-body">
          <!-- form create match -->
        <form id='match_form'method="POST" action = "{% url "match:calendar" %}" class="form-horizontal" role="form">
           {% csrf_token %}
          <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">Name</label>
            <div class="col-sm-10">
              <input type="text" id="name_match" class="form-control" name="name" placeholder="Name">
            </div>
          </div>
          <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">Time</label>
            <div class="col-sm-10">
              <input type="text" id="time_match"  class="form-control datepicker" name="time" placeholder="Time">
            </div>
          </div>
          <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">Place</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" name="place" placeholder="Place">
            </div>
          </div>
          <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">Competitor</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" name="competitor" placeholder="Competitor">
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <button type='button' id="submit_btn" class="btn btn-primary">New match</button>
            </div>
          </div>
        </form>
          <!-- end form -->
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script>
	$(document).ready(function(){

		$('#calendar').fullCalendar({
			header: {
				left: 'prev,next today',
				center: 'title',
				right: 'month,agendaWeek,agendaDay'
			},
            editable: true,
			events: "{% url "match:get_match" %}",
			loading: function(bool) {
				if (bool) $('#loading').show();
				else $('#loading').hide();
			},
            dateFormat: 'mm/dd/yyyy',

            //show modal when click on day cell
            dayClick: function(date, allDay, jsEvent, view) {
                {% if perms.match.can_modify %}
                date_f = $.fullCalendar.formatDate( date,'MM/dd/yyyy')
                if (allDay) {
                    $('#mymodal').modal('show');
                    $('#time_match').val(date_f);
                }else{
                    //alert('Clicked on the slot: ' + date);
                }
                {% endif %}
            }
		})

        // create match on calendar via ajax
        $('#submit_btn').click(function(){
            $("#match_form").submit(function(e){
                var postData = $(this).serializeArray();
                var formURL = $(this).attr("action");
                $.ajax(
                    {
                        url : formURL,
                        type: "POST",
                        data : postData,
                        success:function(data, textStatus, jqXHR)
                        {
                            $('#mymodal').modal('hide');
                            var newEvent = new Object();
                            newEvent.title = $('#name_match').val();
                            newEvent.start = $('#time_match').val();
                            newEvent.url = "/match/detail/" + data;
                            newEvent.allDay = false;
                            $('#calendar').fullCalendar( 'renderEvent', newEvent );
                        },
                        error: function(jqXHR, textStatus, errorThrown)
                        {
                        }
                    });
                e.preventDefault();	//STOP default action
            });
            $("#match_form").submit();
        });

    });
</script>
{% endblock %}

templates/match/detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% block extend_lib %}
    <link rel="stylesheet" href="{% static "bower_components/multiselect/css/multi-select.css" %}"/>
    <script src="{% static "bower_components/multiselect/js/jquery.multi-select.js" %}"></script>
{% endblock %}
{% block title %}match detail{% endblock %}
{% block match %} active {% endblock %}
{% block content %}
    <div class="match-info">
    <h1>{{ match.name|capfirst }}</h1>
    {% if is_modify %}
    <p>
        <span>Action</span>
        <a href="/match/edit/{{ match.id }}">Edit</a>
        <a href="/match/delete/{{ match.id }}">Delete</a>
    </p>
    {% endif %}
    <p><span>Time:</span> {{ match.time|date:"D d M Y" }}</p>
    <p><span>Place:</span> {{ match.place }}</p>
    <p><span>Competitor:</span> {{ match.competitor }}</p>
    <p><span>Result:</span> {{ match.result }}</p>
    </div>
    {% if is_modify %}
    <select multiple="multiple"  id="my-select" name="my-select[]">
      {% for play in all_player %}
           <option value='{{ play.id }}'>
               {% if play.first_name or play.last_name %}
                   {{ play.first_name }} {{ play.last_name }}
               {% else %}
                   {{ play.username }}
               {% endif %}
           </option>
      {% endfor %}
    </select>
    {% else %}
        <p style="font-weight: bold; font-size:1.2em;">List player:</p>
        <ul id="list_player">
            {% for play in all_player %}
                 <li id="list-{{ play.id }}" data-id="{{ play.id }}">
                   {% if play.first_name or play.last_name %}
                       {{ play.first_name }} {{ play.last_name }}
                   {% else %}
                       {{ play.username }}
                   {% endif %}
                 <div id="info-player-{{ play.id }}" style="display: none">
                       <div class="img-user">
                          <img width="100px" height="100px" class="event-cover" src="{{ MEDIA_URL }}{{ play.profile.avatar }}"/>
                       </div>
                       <div class="info">
                        <b>Name: </b><span> {{ play.first_name }} {{ play.last_name }} </span><br>
                        <b>Position: </b><span> {{ play.profile.pos }}</span><br>
                        <b>Number: </b><span> {{ play.profile.num }}</span><br>
                        <b>Email: </b><span> {{ play.email }}</span><br>
                        <b>Contact: </b><span> {{ play.profile.contact }}</span><br>
                       </div>
                 </div>
                 </li>

            {% endfor %}
        </ul>
        {% if user.is_authenticated and perms.match.can_joinmatch %}
            {% if is_join %}
                <button id="join_match" class="btn btn-sm btn-primary">Unjoin</button>
            {% else %}
                <button id="join_match" class="btn btn-sm btn-primary">Join</button>
            {% endif %}
        {% endif %}
    {% endif %}
    <br>
    <div class="">
        <p><b>Comments:</b><p>
        <div id="list_comment">
            {% for comment in match.comment_set.all %}
                {% if comment.comment %}
                <div class="comment row" id="comment-{{ comment.id }}">
                    <div class="col-md-3">
                        <b>{{ comment.creator | escape }} </b> said:
                    </div>
                    <div class="col-md-9 ">
                        <div class="pull-right">
                        <span class="comment-meta">{{ comment.created }}</span>
                        {% if perms.match.can_modify %}
                            <input type="checkbox" class="delete-comment-id" name="comment_id" value="{{ comment.id }}"/>
                        {% endif %}
                        </div>
                    </div>
                    <div style="margin-left: 40px">
                        {{ comment.comment | escape}}
                    </div>
                </div>
                {% endif %}
            {% endfor %}
        </div>
        {% if perms.match.can_modify %}
           <br/><input type="submit" class="btn" id="delete-comment-button" value="Delete comments"/>
        {% endif %}
    </div>

    <div class="comment-form">
                {% if user.is_authenticated %}
                    <form action="" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="is_comment" value="1"/>
                        <label>Your comment</label>
                        {{ commentform.comment }}
                        <br>
                        <input class="btn btn-primary" id="comment-button" type="submit" value="Comment"/>
                    </form>
                {% else %}
                    Please <a href="{% url "account:login" %}?next={% url "match:detail" match.id %}">Login</a> to comment !
                {% endif %}
            </div>
    <br>
    <!-- modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">Reason</h4>
          </div>
          <div class="modal-body">
            <input class="form-control" type="text" id="reason" placeholder="Give me your reason ?"/>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary" onclick="unjoin()">Save changes</button>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <script>
        function unjoin(){
            var reason = $('#reason').val();
            $.ajax({
              url: "/match/remove_player/{{ match.id }}/",
              type: "POST",
              data: {
                  'user_id' : {{ user.id }},
                  'csrfmiddlewaretoken' : '{{ csrf_token }}',
                  'reason' : reason
              },
              success: function(data, textStatus){
                  $('#list-{{ user.id }}').remove();
                  $('#join_match').text("Join");
                  $('#myModal').modal('hide');
                  console.log(data);
              },
              error: function(data, textStatus){

              }
            })
        }
        $(document).ready(function(){
            var count = -1;
            var a = "{{ has_player }}"
            var b = a.split(",")
           $('#my-select').multiSelect({
              selectableHeader: "<div class='custom-header'>Avaiable Player</div>",
              selectionHeader: "<div class='custom-header'>Attended player</div>",
              afterInit: function(ms) {
                $('#my-select').multiSelect('select', b);
              },
              afterSelect: function(values){
                  console.log(values[0]);

                  count ++;
                  console.log(count);
                  if (count > 0) {
                      $.ajax({
                          url: "/match/add_player/{{ match.id }}/",
                          type: "POST",
                          data: {
                              'user_id' : values[0],
                              'csrfmiddlewaretoken' : '{{ csrf_token }}'
                          },
                          success: function(data, textStatus){

                          },
                          error: function(data, textStatus){

                          }
                      })
                  }
              },
              afterDeselect: function(values){
                 $.ajax({
                      url: "/match/remove_player/{{ match.id }}/",
                      type: "POST",
                      data: {
                          'user_id' : values[0],
                          'csrfmiddlewaretoken' : '{{ csrf_token }}',
                          'reason' : ''
                      },
                      success: function(data, textStatus){

                      },
                      error: function(data, textStatus){

                      }
                  })
              }
           });

            $('#a').click(function(){
                $('#my-select').multiSelect('select', ['quoc']);
                return true
            })

            $('#join_match').click(function(){
                var self = $(this);
                if (self.text() == "Unjoin"){
                    $('#myModal').modal('show');
                }
                else{
                    $.ajax({
                      url: "/match/add_player/{{ match.id }}/",
                      type: "POST",
                      data: {
                          'user_id' : {{ user.id }},
                          'csrfmiddlewaretoken' : '{{ csrf_token }}'
                      },
                      success: function(data, textStatus){
                          var play = data[0];
                          html = '<li id="list-{{ user.id }}" data-id="{{ user.id }}" >{% if user.first_name or user.last_name %}{{ user.first_name }} {{ user.last_name }}{% else %}{{ user.username }}{% endif %}'
                          html += '<div id="info-player-'+play.id+'" style="display: none">'
                          html += '<div class="img-user">'
                          html += '<img width="100px" height="100px" class="event-cover" src="{{ MEDIA_URL }}'+play.avatar+'"/>'
                          html += '</div>'
                          html += '<div class="info">'
                          html += '<b>Name: </b><span>'+ play.first_name + ' '+ play.last_name +'</span><br>'
                          html += '<b>Position: </b><span>'+ play.pos +'</span><br>'
                          html += '<b>Number: </b><span>'+ play.num +'</span><br>'
                          html += '<b>Email: </b><span>'+ play.email +'</span><br>'
                          html += '<b>Contact: </b><span>'+ play.contact +'</span><br>'
                          html += '</div>'
                          html += '</div>'
                          html += '</li>'
                          $('#list_player').append(html)
                          self.text("Unjoin");
                      },
                      error: function(data, textStatus){

                      }
                    })
                }
            })
            $('#delete-comment-button').click(function(){
                var list_comment_id = new Array()
                //get list comment id
                $('.delete-comment-id').each(function(){
                    if($(this).is(":checked")) {
                        list_comment_id.push($(this).val());
                    }
                });
                $.ajax({
                      url: "/match/detail/{{ match.id }}/",
                      type: "POST",
                      data: {
                          'is_delete_comment': 1,
                          'comment_id' : list_comment_id,
                          'csrfmiddlewaretoken' : '{{ csrf_token }}'
                      },
                      success: function(data, textStatus){
                          $('.delete-comment-id').each(function(){

                             if($(this).is(":checked")) {
                                 var id = $(this).val()
                                 $('#comment-' + id).fadeOut('slow');
                                  setTimeout(function(){$('#comment-' + id).remove()}, 1000);
                             }
                            });
                      },
                      error: function(data, textStatus){

                      }
                    })
                return false;
            });
            var list_player = $('#list_player');
            list_player.on("mouseover", "li", function(){
                var cl = '#info-player-' + $(this).data('id')
                list  =  $(this);
                list.addClass('visible');
                $(cl).addClass('info-player').css('display','block');
            });
            list_player.on("mouseout", "li", function(){
                var cl = '#info-player-' + $(this).data('id')
                list  =  $(this);
                list.removeClass('visible');
                $(cl).removeClass('info-player').css('display','none');
            });
        })
    </script>
{% endblock %}

templates/match/match_form.html
{% extends 'base.html' %}
{% block title %}
    {% if form_type == 'edit' %}
    Update Match
    {% else %}
    Create Match
    {% endif %}
{% endblock %}
{% block create %} active {% endblock %}
{% block content %}

    {% if form_type == 'edit' %}
    <h3>Update Match</h3>
    {% else %}
    <h3>Create Match</h3>
    {% endif %}
    <form role="form" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ match_form }}
    <br>
    <button type="submit" class="btn btn-primary">Save</button>
    </form>
    <script>
        $(document).ready(function(){
            $('#time').datepicker();
        })
    </script>
{% endblock %}