FootballClub/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
  url(r'^$', 'match.views.index'),
  url(r'^account/', include('account.urls', namespace='account')),
  url(r'^accounts/', include('accounts.urls', namespace='accounts')),
  url(r'^admin/', include(admin.site.urls)),
  url(r'^match/', include('match.urls', namespace='match')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.conf.urls import patterns, url
from account import views

urlpatterns = patterns('',
  url(r'^$', views.index),
  url(r'^profile/$', views.profile, name='profile'),
	url(r'^list_player/(?P<user_id>.+)/$', views.edit, name='edit'),
	url(r'^delete/(?P<user_id>.+)/$', views.delete, name='delete'),
	url(r'^login/$', views.site_login, name='login'),
	url(r'^logout/$', views.site_logout, name='logout'),
	url(r'^register/$', views.register, name='register'),
	url(r'^list_player/$', views.list_player, name='list_player'),
)

match/urls.py
from django.conf.urls import patterns, include, url
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from match import views
admin.autodiscover()

urlpatterns = patterns('',
  url(r'^$', views.index, name='index'),
  url(r'^add/$', views.add, name='add'),
  url(r'^edit/(?P<match_id>\d+)/$', views.edit, name='edit'),
  url(r'^detail/(?P<match_id>\d+)/$', views.detail, name='detail'),
	url(r'^delete/(?P<match_id>\d+)/$', views.delete, name='delete'),
	url(r'^add_player/(?P<match_id>\d+)/$', views.add_player, name='add_player'),
	url(r'^remove_player/(?P<match_id>\d+)/$', views.remove_player, name='remove_player'),
  url(r'^calendar/$', views.calendar, name='calendar'),
  url(r'^get_match/$', views.get_match, name='get_match'),
)

templates/base.html
{% load staticfiles %}
{% load base_ex %}
<!DOCTYPE html>
<html lang="en">
<head>

    <link rel="stylesheet" href="{% static "bower_components/bootstrap/dist/css/bootstrap.min.css" %}" media="screen">
    <link rel="stylesheet" href="{% static "css/match_index.css" %}"/>
    <link rel="stylesheet" href="{% static "css/image_hover.css" %}"/>
    <link rel="stylesheet" href="{% static "css/daterangepicker-bs3.css" %}"/>
    <link href='http://fonts.googleapis.com/css?family=Comfortaa' rel='stylesheet' type='text/css'>
    <script src="{% static "bower_components/jquery/jquery.min.js" %}"></script>
    <script src="{% static "bower_components/bootstrap/dist/js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/daterangepicker.js" %}"></script>
    <script src="{% static "js/bootstrap-datepicker.js" %}"></script>
    <script src="{% static "js/moment.min.js" %}"></script>
    <script src="{% static "js/ajax_setup.js"%}"></script>

    {% block extend_lib %}

    {% endblock %}
    <style type="text/css">@import url("{% static "css/datepicker.css"%}");</style>
    <title>{% block title %}Matchs{% endblock %}</title>

</head>

<body>
    <div id="share-wrapper">
        <ul class="share-inner-wrp">
            <!-- Facebook -->
            <li class="facebook button-wrap"><a href="#">Facebook</a></li>

            <!-- Twitter -->
            <li class="twitter button-wrap"><a href="#">Tweet</a></li>

            <!-- Google -->
            <li class="google button-wrap"><a href="#">Plus</a></li>

            <!-- Email -->
            <li class="email button-wrap"><a href="#">Email</a></li>
        </ul>
    </div>
	<div id="container">
		<div id="sidebar" >
			{% block sidebar %}
            <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
   <div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <a class="navbar-brand" href="#">HTK-INC</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav menu">
      <li class="{% block match %}{% endblock %}"><a href="{% url "match:index" %}">Match Center</a></li>
    <li class="{% block calendar %}{% endblock %}"><a href="{% url "match:calendar" %}">Calendar</a></li>
      {% if user.is_authenticated %}
      <li class="{% block profile %}{% endblock %}"><a href="{% url "account:profile" %}">Profile</a></li>
          {% if perms.match.can_modify %}
      <li class="{% block list %}{% endblock %}"><a href="{% url "account:list_player" %}">List player</a></li>
      <li class="{% block create %}{% endblock %}"><a href="{% url "match:add" %}">Create Match</a></li>
          {% endif %}
      {% endif %}
    </ul>
    <ul class="nav navbar-nav navbar-right">
      {% if user.is_authenticated %}
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            {{ user.first_name }} {{ user.last_name }} <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="{% url "account:logout" %}">Logout</a></li>

        </ul>
      </li>
      {% else %}
          <li><a href="{% url "account:login" %}">Login</a></li>
      {% endif %}
    </ul>
  </div><!-- /.navbar-collapse -->
       </div>
</nav>
			{% endblock %}
		</div>

		<div id="content" class="container-fluid">
				<div class="container">
                    <div class="match_index">
					    {% block content %}{% endblock %}
                    </div>
                </div>
		</div>
    </div>
<script>
    $(document).ready(function() {
	var pageTitle = document.title; //HTML page title
	var pageUrl = location.href; //Location of the page


	//user hovers on the share button
	$('#share-wrapper li').hover(function() {
		var hoverEl = $(this); //get element

		//browsers with width > 699 get button slide effect
		if($(window).width() > 699) {
			if (hoverEl.hasClass('visible')){
				hoverEl.animate({"margin-left":"-117px"}, "fast").removeClass('visible');
			} else {
				hoverEl.animate({"margin-left":"0px"}, "fast").addClass('visible');
			}
		}
	});


	//user clicks on a share button
	$('.button-wrap').click(function(event) {
			var shareName = $(this).attr('class').split(' ')[0]; //get the first class name of clicked element

			switch (shareName) //switch to different links based on different social name
			{
				case 'facebook':
					var openLink = 'https://www.facebook.com/sharer/sharer.php?u=' + encodeURIComponent(pageUrl) + '&amp;title=Football Management by Django';
					break;
				case 'twitter':
					var openLink = 'http://twitter.com/home?status=' + encodeURIComponent(pageTitle + ' ' + pageUrl);
					break;
				case 'google':
					var openLink = 'https://plus.google.com/share?url=' + encodeURIComponent(pageUrl) + '&amp;title=' + encodeURIComponent(pageTitle);
					break;
				case 'email':
					var openLink = 'mailto:?subject=' + pageTitle + '&body=Found this useful link for you : ' + pageUrl;
					break;
			}

		//Parameters for the Popup window
		winWidth 	= 650;
		winHeight	= 450;
		winLeft   	= ($(window).width()  - winWidth)  / 2,
		winTop    	= ($(window).height() - winHeight) / 2,
		winOptions   = 'width='  + winWidth  + ',height=' + winHeight + ',top='    + winTop    + ',left='   + winLeft;

		//open Popup window and redirect user to share website.
		window.open(openLink,'Share This Link',winOptions);
		return false;
	});
});
</script>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
    {% if user.is_authenticated %}
        <h1>{{ user.username }}</h1>
    {% endif %}
    {% if new_match %}
        <p>{{ new_match.id }}</p>
        <p>{{ new_match.name }}</p>
        <p>{{ new_match.place }}</p>
    {% endif %}
    <h1>Football Club MG</h1>
</body>
</html>